### ISSUE TITLE
Copying to clipboard issue

### ISSUE THREAD

**Issue by elythh** [SergioRibera/sss#6]
Hello, I don't seem to be able to copy my screenshots to my clipboard using sss and wl-copy. \
If I use the example command from the README `sss --area "$(slurp)" --author "SergioRibera" -o raw | wl-copy`, my clipboard is still empty

**Comment by SergioRibera** [comment]
Check if you have the main version or the release version, it seems to me that the release version does not yet have that feature.

You could try `-o raw` without the Pipe to `wl-copy` to see what comes out

**Comment by elythh** [comment]
![test](https://github.com/SergioRibera/sss/assets/50964650/6102659d-741e-438f-b972-4f048cd34875)
running `sss_cli 0.1.4`

thing is that it used to work

**Comment by elythh** [comment]
<details>

```
�PNG


```
</details>

**Comment by SergioRibera** [comment]
Ok, this problem comes from wl-copy, try `wl-copy -p`, are you in a wayland environment?

**Comment by elythh** [comment]
Oh you're right. I'll close the issue since it's not from sss. Also yes I'm in Wayland
